# Generated by Django 3.0.3 on 2020-07-22 17:15

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0005_auto_20200723_0012'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
