# Generated by Django 3.0.3 on 2020-07-23 05:44

import core.models_settings
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200723_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', core.models_settings.ContentTypeRestrictedFileFieldProtected(storage=core.models_settings.ProtectedFileSystemStorage(), upload_to=core.models_settings.get_cv_path)),
                ('ktp', core.models_settings.ContentTypeRestrictedFileFieldProtected(storage=core.models_settings.ProtectedFileSystemStorage(), upload_to=core.models_settings.get_ktp_path)),
                ('npwp', core.models_settings.ContentTypeRestrictedFileFieldProtected(blank=True, default='', storage=core.models_settings.ProtectedFileSystemStorage(), upload_to=core.models_settings.get_npwp_path)),
                ('certification', core.models_settings.ContentTypeRestrictedFileFieldProtected(storage=core.models_settings.ProtectedFileSystemStorage(), upload_to=core.models_settings.get_certification_path)),
                ('portofolio', core.models_settings.ContentTypeRestrictedFileFieldProtected(storage=core.models_settings.ProtectedFileSystemStorage(), upload_to=core.models_settings.get_portofolio_path)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='admin', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='mentor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentor_data',
            },
        ),
    ]
