# Generated by Django 3.0.3 on 2020-07-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentordata',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Waiting'), ('DE', 'Decline')], default='WA', max_length=2),
        ),
    ]
