# Generated by Django 3.0.3 on 2020-07-27 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_essay_essayanswer_quiz_quizchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='course',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
