# Generated by Django 3.0.3 on 2020-07-28 05:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sessiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_no',
            field=models.CharField(blank=True, default=core.models.increment_invoice_number, max_length=500, null=True),
        ),
    ]
