# Generated by Django 3.0.3 on 2020-07-28 18:30

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0021_auto_20200728_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Essay',
            new_name='Exam',
        ),
        migrations.RenameModel(
            old_name='EssayAnswer',
            new_name='ExamAnswer',
        ),
        migrations.RemoveField(
            model_name='quizchoice',
            name='quiz',
        ),
        migrations.RenameField(
            model_name='examanswer',
            old_name='essay',
            new_name='exam',
        ),
        migrations.AlterModelTable(
            name='exam',
            table='exam',
        ),
        migrations.AlterModelTable(
            name='examanswer',
            table='exam_anwer',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizChoice',
        ),
    ]
