# Generated by Django 3.0.3 on 2020-07-29 05:16

import core.models_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200729_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentordata',
            name='npwp',
            field=core.models_utils.ContentTypeRestrictedFileFieldProtected(blank=True, default='', null=True, storage=core.models_utils.ProtectedFileSystemStorage(), upload_to=core.models_utils.get_npwp_path),
        ),
    ]
