# Generated by Django 3.0.3 on 2020-07-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200729_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
