# Generated by Django 3.0.3 on 2020-07-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_course_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='close_at',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
