# Generated by Django 3.0.3 on 2020-07-30 07:46

import core.models_utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_exam_close_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=core.models_utils.ContentTypeRestrictedFileField(blank=True, default='', null=True, upload_to=core.models_utils.get_category_image_path),
        ),
        migrations.CreateModel(
            name='ExamData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', core.models_utils.ContentTypeRestrictedFileFieldProtected(storage=core.models_utils.ProtectedFileSystemStorage(), upload_to=core.models_utils.get_project_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_data',
            },
        ),
    ]
