# Generated by Django 3.0.3 on 2020-07-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200730_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamData',
            new_name='ExamProject',
        ),
        migrations.AlterModelTable(
            name='examproject',
            table='exam_project',
        ),
    ]
