# Generated by Django 3.0.3 on 2020-08-03 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_examreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examproject',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examproject',
            name='user',
        ),
        migrations.AddField(
            model_name='examproject',
            name='exam_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ExamAnswer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='answer',
            field=models.TextField(default=''),
        ),
    ]
