# Generated by Django 3.0.3 on 2020-08-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200805_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examreport',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examreport',
            name='user',
        ),
        migrations.AddField(
            model_name='examreport',
            name='exam_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ExamAnswer'),
            preserve_default=False,
        ),
    ]
