# Generated by Django 3.0.3 on 2020-08-06 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200807_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='examreport',
            name='summary',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExamSummary',
        ),
    ]
