# Generated by Django 3.1 on 2020-08-10 07:35

from django.db import migrations,models



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200810_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
