# Generated by Django 3.1 on 2020-08-10 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200810_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examanswer',
            old_name='report',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='library',
            name='summary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='sdf', max_length=256),
            preserve_default=False,
        ),

    ]
