# Generated by Django 3.1 on 2020-08-10 22:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0044_auto_20200811_0534'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='examanswer',
            table='exam_answer',
        ),
    ]
