# Generated by Django 3.1 on 2020-08-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20200811_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentordata',
            name='no_ktp',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
