# Generated by Django 3.1 on 2020-08-13 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_mentordata_no_ktp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentordata',
            name='no_ktp',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
