# Generated by Django 3.1 on 2020-08-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20200813_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentordata',
            name='no_ktp',
            field=models.CharField(max_length=20),
        ),
    ]
