# Generated by Django 3.1 on 2020-08-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20200813_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['start_at']},
        ),
    ]
