# Generated by Django 3.1 on 2020-08-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_course_course_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='category_pic',
        ),
    ]
