# Generated by Django 3.1 on 2020-08-18 18:02

import core.models_utils
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20200816_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['close_at']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_url',
        ),
        migrations.AddField(
            model_name='order',
            name='admin',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_query_name='admin', to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_pic',
            field=core.models_utils.ContentTypeRestrictedFileFieldProtected(default=datetime.datetime(2020, 8, 18, 18, 2, 29, 487071, tzinfo=utc), storage=core.models_utils.ProtectedFileSystemStorage(), upload_to=core.models_utils.get_order_attachment_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
