# Generated by Django 3.1 on 2020-08-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20200821_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url_project',
            field=models.URLField(blank=True, null=True),
        ),
    ]
