# Generated by Django 3.1 on 2020-08-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20200825_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='mentordata',
            name='status',
            field=models.CharField(choices=[('AC', 'Diterima'), ('WA', 'Menunggu Konfirmasi'), ('DE', 'TIdak Valid')], default='WA', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WP', 'Menunggu Pembayaran'), ('WC', 'Menunggu Konfirmasi'), ('CO', 'Selesai'), ('DE', 'TIdak Valid')], default='WP', max_length=2),
        ),
    ]
