# Generated by Django 3.1 on 2020-08-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20200826_0934'),
        ('core', '0061_auto_20200826_0159'),
    ]

    operations = [
    ]
