# Generated by Django 3.1 on 2020-08-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20200827_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentordata',
            options={'ordering': ['mentor']},
        ),
    ]
