# Generated by Django 3.1 on 2020-09-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20200827_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentordata',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentordata',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
