# Generated by Django 3.1 on 2020-09-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20200902_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url_meet',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
