# Generated by Django 3.1 on 2020-09-11 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_coursedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('AU', 'Semua user'), ('MO', 'Hanya untuk invited_user'), ('MF', 'Untuk semua user, tapi invited_user gratis')], default='AU', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='invited_user',
            field=models.ManyToManyField(related_query_name='invited_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='link_invitation',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_course', related_query_name='admin_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CourseData',
        ),
    ]
