# Generated by Django 3.1 on 2020-09-11 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20200911_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='invited_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
