# Generated by Django 3.1 on 2020-09-11 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20200911_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
