# Generated by Django 3.1 on 2020-09-11 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20200911_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='invited_user',
            field=models.ManyToManyField(related_name='invited_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
