# Generated by Django 3.1 on 2020-09-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20200911_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='invited_user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='link_invitation',
        ),
    ]
