# Generated by Django 3.1 on 2020-09-17 07:53

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0078_mitra'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mitra',
            table='mitra',
        ),
    ]
