# Generated by Django 3.1 on 2020-09-17 07:54

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0079_auto_20200917_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mitra',
        ),
    ]
