# Generated by Django 3.1 on 2020-09-17 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_mitra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitra',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
