# Generated by Django 3.1 on 2020-09-18 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_course_mitra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitra',
            name='user',
        ),
        migrations.CreateModel(
            name='MitraUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_co_host', models.BooleanField(default=False)),
                ('mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mitra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mitra_user',
            },
        ),
    ]
