# Generated by Django 3.1 on 2020-09-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20200918_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentordata',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
