# Generated by Django 3.1 on 2020-09-22 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_mentordata_is_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'intitution',
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='mentordata',
            name='is_partner',
        ),
        migrations.AddField(
            model_name='mentordata',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.institution'),
        ),
    ]
