# Generated by Django 3.1 on 2020-09-23 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20200922_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitraInvitedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mitra')),
            ],
            options={
                'db_table': 'mitra_invited_user',
            },
        ),
    ]
