# Generated by Django 3.1 on 2020-09-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_mitrainviteduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mitra',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='mitra',
            name='email',
            field=models.EmailField(default='ivanrputra@gmail.com', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
