# Generated by Django 3.1 on 2020-09-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20200923_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitra',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='mitra',
            name='status',
            field=models.CharField(choices=[('WC', 'Menunggu Konfirmasi'), ('CO', 'Selesai'), ('DE', 'TIdak Valid')], default='WC', max_length=2),
        ),
    ]
