# Generated by Django 3.1 on 2020-09-23 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_user_is_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_partner',
        ),
    ]
