# Generated by Django 3.1 on 2020-09-25 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20200924_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitra',
            options={'ordering': ['status', 'updated_at']},
        ),
    ]
