# Generated by Django 3.1 on 2020-09-29 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20200925_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitrainviteduser',
            name='invited_by',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitrainviteduser',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='mitrainviteduser',
            unique_together={('email', 'mitra')},
        ),
    ]
