# Generated by Django 3.1 on 2020-10-10 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_mitrainviteduser_last_send_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitrainviteduser',
            name='resend_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resend_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
